### ISSUE TITLE
Un-Classified based on a threshold score

### ISSUE THREAD

**Issue by ashwarhussain** [erfan-ghadery/Unsupervised-Aspect-Category-Detection#1]
Hello Erfan,

I was looking at this implementation and thanks for this Git Hub repository.

I have one question .. if I want to have a un-classified category and based on a threshold of Cosine Similarity value if I want to sent a particular text to Un-classified category then is it possible?

Suppose say my Text is "Corona Virus is creating havoc" but in category and keywords I have all yelp related like food, service, ambience etc then this text ideally should go to Un-classified bucket. is that possible with this implementation?

Thanks much,
Ashwar.

**Comment by erfan-ghadery** [comment]
@ashwarhussain Hi Ashwar, thanks for your interest. You can simply add your additional desired categories to the list of predefined categories in `dataLoader.py`.

```
self.category_label_num = 
{
    'service': 0,
    'food': 1,
    'price': 2,
    'ambience': 3,
    'anecdotes/miscellaneous': 4,
    'YOUR_Desired_Category': 5

}
```
